pipeline:
  identifier: Build_harness_ci_example_1717657336656
  name: Build harness-ci-example
  orgIdentifier: default
  projectIdentifier: Generative_AI
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.KrishnaIndium
        repoName: harness-ci-example
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    shell: Sh
                    command: |-
                      npm install
                      npm test
                  timeout: ""
                  type: Run
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: Gen_Docker_Hub
                    repo: docskrishna/gen_ai
                    tags:
                      - latest
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
    - stage:
        name: CFT
        identifier: CFT
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: CreateStack
                  name: CreateStack_1
                  identifier: CreateStack_1
                  spec:
                    provisionerIdentifier: CreateStack
                    configuration:
                      stackName: s3-stack-harness
                      region: ap-south-1
                      templateFile:
                        type: Inline
                        spec:
                          templateBody: asdfg
                      roleArn: ""
                      connectorRef: aws_connnect
                  timeout: 10m
        tags: {}
