pipeline:
  identifier: Build_harness_ci_example_1717582249405
  name: Build harness-ci-example
  orgIdentifier: default
  projectIdentifier: GenAI
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.KrishnaIndium
        repoName: harness-ci-example
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: installdependencies
                  name: install dependencies
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
              - step:
                  identifier: test
                  name: test
                  spec:
                    command: npm run test
                  timeout: ""
                  type: Run
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
    - stage:
        name: stage1
        identifier: stage1
        description: ""
        type: Custom
        spec:
          environment:
            environmentRef: stage_env1
            deployToAll: false
            infrastructureDefinitions:
              - identifier: stage_infra1
          execution:
            steps:
              - step:
                  type: CreateStack
                  name: CreateStack_1
                  identifier: CreateStack_1
                  spec:
                    provisionerIdentifier: Create_Stack
                    configuration:
                      stackName: s3-harness
                      connectorRef: aws_connector
                      region: us-east-1
                      templateFile:
                        type: Inline
                        spec:
                          templateBody: |
                            AWSTemplateFormatVersion: '2010-09-09'

                            Parameters:
                              S3BucketName:
                                Type: String
                                Description: S3 Bucket Name
                                Default: "Harness-cft-template-s3"

                              TagTRCDescription:
                                Type: String
                                Description: TRC-Description
                                Default: "ZZ - Captures 2.0 Sandbox"
                              TagTRCSector:
                                Type: String
                                Description: TRC-Sector
                                Default: "ZZ"
                              TagTRCOwner:
                                Type: String
                                Description: TRC-Owner
                                Default: "Sanjay Jha"
                              TagTRCPractice:
                                Type: String
                                Description: TRC-Practice
                                Default: "ZAT"
                              TagTRCOrgCode:
                                Type: String
                                Description: TRC-OrgCode
                                Default: "6.A.IRV.ZZ.ZAT"
                              TagTRCAllocationCode:
                                Type: String
                                Description: TRC-AllocationCode
                                Default: "310549"
                              TagProject:
                                Type: String
                                Description: Project
                                Default: "Captures 2.0"
                              TagCreatedBy:
                                Type: String
                                Description: Created by
                                Default: "Krishnamoorthy"

                            Resources:
                              S3Bucket:
                                Type: AWS::S3::Bucket
                                Properties:
                                  BucketName: !Ref S3BucketName
                                  PublicAccessBlockConfiguration:
                                    BlockPublicAcls: false
                                  OwnershipControls:
                                    Rules:
                                      - ObjectOwnership: ObjectWriter
                                  VersioningConfiguration:
                                    Status: Enabled
                                  BucketEncryption:
                                    ServerSideEncryptionConfiguration:
                                      - ServerSideEncryptionByDefault:
                                          SSEAlgorithm: AES256
                                  WebsiteConfiguration:
                                    IndexDocument: index.html
                                    ErrorDocument: error.html
                                  Tags:
                                    - Key: "Name"
                                      Value: !Ref S3BucketName
                                    - Key: "TRC-Description"
                                      Value: !Ref TagTRCDescription
                                    - Key: "TRC-Sector"
                                      Value: !Ref TagTRCSector
                                    - Key: "TRC-Owner"
                                      Value: !Ref TagTRCOwner
                                    - Key: "TRC-Practice"
                                      Value: !Ref TagTRCPractice
                                    - Key: "TRC-OrgCode"
                                      Value: !Ref TagTRCOrgCode
                                    - Key: "TRC-AllocationCode"
                                      Value: !Ref TagTRCAllocationCode
                                    - Key: "Project"
                                      Value: !Ref TagProject
                                    - Key: "CreatedBy"
                                      Value: !Ref TagCreatedBy
                                # DeletionPolicy: Retain
                                # UpdateReplacePolicy: Retain
                      roleArn: ""
                  timeout: 10m
        tags: {}
  notificationRules:
    - name: stage_test
      identifier: stage_test
      pipelineEvents:
        - type: StageFailed
          forStages:
            - AllStages
        - type: StageSuccess
          forStages:
            - AllStages
      notificationMethod:
        type: Email
        spec:
          userGroups: []
          recipients:
            - krishnamoorthy.v@indiumsoft.com
      enabled: true
