pipeline:
  identifier: Build_harness_ci_example_1717582249405
  name: Build harness-ci-example
  orgIdentifier: default
  projectIdentifier: GenAI
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.KrishnaIndium
        repoName: harness-ci-example
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: installdependencies
                  name: install dependencies
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
              - step:
                  identifier: test
                  name: test
                  spec:
                    command: npm run test
                  timeout: ""
                  type: Run
              - step:
                  type: BuildAndPushECR
                  name: BuildAndPushECR_1
                  identifier: BuildAndPushECR_1
                  spec:
                    connectorRef: aws_connector
                    region: us-east-1
                    account: "562041613760"
                    imageName: harness-poc:latest 562041613760.dkr.ecr.us-east-1.amazonaws.com/harness-poc
                    tags:
                      - latest
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
  notificationRules:
    - name: stage_test
      identifier: stage_test
      pipelineEvents:
        - type: StageFailed
          forStages:
            - AllStages
        - type: StageSuccess
          forStages:
            - AllStages
      notificationMethod:
        type: Email
        spec:
          userGroups: []
          recipients:
            - krishnamoorthy.v@indiumsoft.com
      enabled: true
