pipeline:
  identifier: Build_harness_ci_example_1688909254532
  name: Build harness-ci-example
  orgIdentifier: default
  projectIdentifier: project1
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: Krishna-Indium/harness-ci-example
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: npm install
              - step:
                  type: Run
                  name: Run_2
                  identifier: Run_2
                  spec:
                    shell: Sh
                    command: npm test
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: docker_pat
                    repo: docskrishna/harness_repo
                    tags:
                      - latest
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
        type: CI
